In [1]:
import PG

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Q_Net(nn.Module):
    
    def __init__(self):
        super(Q_Net, self).__init__()
        self.main = nn.Sequential(
                nn.Linear(4, 30),
                nn.ReLU(True),
                nn.Linear(30, 25),
                nn.ReLU(True),
                nn.Linear(25, 2),
                nn.Softmax()
            )

    def forward(self, X):
        #print(f'x: {X}')
        o = self.main(X)
        #print(o)
        return o

In [3]:
import gym
env = gym.make('CartPole-v1')

In [4]:
device = torch.device('cpu')

In [5]:
# xavier uniform weight initialization
def init_weights(m):
    if type(m) == nn.Linear:
        torch.nn.init.xavier_uniform(m.weight)
        m.bias.data.fill_(0.01)

In [6]:
p_net = Q_Net()
#p_net.apply(init_weights)

In [7]:
agent = PG.PG_Agent(p_net, device, env)

/home/rick/Documents/ai_snake/ai_playing_snake/ai/PG.py:17: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  torch.nn.init.xavier_uniform(m.weight)
/home/rick/.local/lib/python3.7/site-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))


In [ ]:
for i in range(10000):
    render = i % 100 == 0
    agent.train_episode(render=render)
    

/home/rick/.local/lib/python3.7/site-packages/torch/nn/modules/container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


total reward: 28.0
total reward: 20.0
total reward: 84.0
total reward: 134.0


In [9]:
env.action_space.n

2

In [1]:
env.close()

NameError: name 'env' is not defined

In [7]:
agent.train_episode(render=True)

tensor([[0.5085, 0.4915],
        [0.5062, 0.4938],
        [0.5081, 0.4919],
        [0.5062, 0.4938],
        [0.5078, 0.4922],
        [0.5207, 0.4793],
        [0.5393, 0.4607],
        [0.5207, 0.4793],
        [0.5402, 0.4598],
        [0.5217, 0.4783],
        [0.5124, 0.4876],
        [0.5230, 0.4770],
        [0.5433, 0.4567],
        [0.5627, 0.4373],
        [0.5830, 0.4170],
        [0.6038, 0.3962],
        [0.6248, 0.3752],
        [0.6462, 0.3538],
        [0.6679, 0.3321]], device='cuda:0', grad_fn=<CatBackward>)
tensor([1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       device='cuda:0')
total reward: 19.0


In [8]:
env.close()

In [20]:
torch.cat([torch.tensor([[[1., 1.]]]), torch.tensor([[[1., 1.]]])], dim =-1)

tensor([[[1., 1., 1., 1.]]])

In [2]:
import torch.nn.functional as F

In [3]:
F.leaky_relu

<function torch.nn.functional.leaky_relu(input, negative_slope=0.01, inplace=False)>

In [16]:
nn.Softmax(dim=1)(torch.tensor([[2,1], [2,1]], dtype=torch.float))

tensor([[0.7311, 0.2689],
        [0.7311, 0.2689]])

In [10]:
from torch import tensor

In [12]:
btch = [tensor([0.4971, 0.5029]), tensor([0.4871, 0.5129])]

In [14]:
torch.stack(btch)

tensor([[0.4971, 0.5029],
        [0.4871, 0.5129]])